displayName=NPC Kill Counter
author=PieterPost43
description=Tracks kills per NPC type, with options to reset a single NPC or all of them
tags=npc,kill,counter,tracker,pvm
plugins=com.nkc.NpcKillCountPlugin
version=
build=standard
