displayName=NPC Kill Counter
author=Guillaume
description=Houdt kills per NPC-type bij, met de mogelijkheid om per soort of alles te resetten
tags=npc,kill,counter,tracker,pvm
plugins=com.nkc.NpcKillCountPlugin
version=
build=standard
